version: '3.8'

services:
	# Serviço do Banco de Dados MySQL
	db:
	  image: mysql:8.0
	  container_name: flop-db
	  restart: unless-stopped
	  environment:
	    # Essas variáveis são do nosso arquivo .env
	    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
	    MYSQL_DATABASE: ${MYSQL_DATABASE}
	  ports:
	    # Mapeia a porta do host para a do contêiner para podermos conectar com um cliente de BD
	    - "3306:3306"
	  volumes:
	    - db_data:/var/lib/mysql

volumes:
  # Define um volume nomeado para persistir os dados do banco de dados
  db_data: