INSERT INTO praia (nome_praia) VALUES 
('Praia da Armação'),
('Praia da Barra da Lagoa'),
('Praia da Cachoeira do Bom Jesus'),
('Praia da Costeira da Armação'),
('Praia da Costeira do Ribeirão'),
('Praia da Daniela'),
('Praia da Galheta'),
('Praia da Ilha do Campeche'),
('Praia da Joaquina'),
('Praia da Lagoinha do Leste'),
('Praia da Mole'),
('Praia da Saudade'),
('Praia da Solidão'),
('Praia da Tapera'),
('Praia do Balneário'),
('Praia do Bom Abrigo'),
('Praia do Caldeirão'),
('Praia do Campeche'),
('Praia do Campeche Sul'),
('Praia do Farol de Naufragados'),
('Praia do Forte'),
('Praia do Forte São José da Ponta Grossa'),
('Praia do Forte do Santinho'),
('Praia do Gravatá'),
('Praia do Lagoinha do Norte'),
('Praia do Matadeiro'),
('Praia do Moçambique'),
('Praia do Morro das Pedras'),
('Praia do Pântano do Sul'),
('Praia do Ribeirão da Ilha'),
('Praia do Saquinho'),
('Praia do Sambaqui'),
('Praia do Santinho'),
('Praia do Tinguá'),
('Praia dos Ingleses'),
('Praia dos Naufragados'),
('Praia de Canasvieiras'),
('Praia de Cacupé'),
('Praia de Jurerê'),
('Praia de Jurerê Internacional');
