package com.vitalu.flop.model.enums;

public enum Condicoes {

	NUBLADO, VENTO, CHUVA, SOL, LOTADA, AGUA_VIVA, LIXO, LIMPA, MAR_ONDAS, MAR_CALMO, MUSICA, ALIMENTACAO, SALVA_VIDAS,
	AGUA_GELADA, ESTACIONAMENTO
}
